/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ndk_jni_JNIACT */

#ifndef _Included_cn_edaijia_android_client_AppInfo
#define _Included_cn_edaijia_android_client_AppInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_edaijia_android_client_AppInfo
 * Method:    get
 * 
 */
JNIEXPORT jstring JNICALL Java_cn_edaijia_android_client_AppInfo_get
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
